# Generated by Django 3.0.8 on 2020-07-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='tite',
            new_name='title',
        ),
    ]
