# Generated by Django 3.0.8 on 2020-07-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200728_0630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='added_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
    ]
